# Site settings
title: CodeFeedr
subtitle: Streaming Software Analytics
email: codefeedr@gmail.com
#description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://codefeedr.github.io" # the base hostname & protocol for your site
author: The CodeFeedr project
street_address: van Mourik Broekmanweg 6
university: TU Delft EWI / ST
office: Room W4.560
city: Delft
zip_code: NL-2628 XE
country: the Netherlands

company_address: Rembrandt Tower, 15th floor
company_address_2: Amstelplein 1
company: Software Improvement Group
company_city: Amsterdam
company_zip_code: NL-1096 HA

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
github_url: https://github.com/codefeedr
slack_url:
twitter_url: https://twitter.com/codefeedr


# Build settings
timezone: "Europe/Amsterdam"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

sass:
  style: compressed
