# Site settings
title: CodeFeedr
subtitle: Streaming Software Analytics
email: codefeedr@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://codefeedr.github.io" # the base hostname & protocol for your site
author: The CodeFeedr project
street_address: Mekelweg 4
university: TU Delft EWI / ST
office: Room 08.140
city: Delft
zip_code: NL-2628 CD
country: the Netherlands


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
github_url: https://github.com/codefeedr
slack_url:
twitter_url: https://twitter.com/codefeedr


# Build settings
timezone: "Europe/Amsterdam"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

sass:
  style: compressed
